### PR TITLE
Add basic cat helpers

### LINKED ISSUE #8: Integrate cat helpers
```
cat_line <- function(..., file = "") {
  cat(..., "\n", sep = "", file = file)
}

cat_kable <- function(x, ..., file = "") {
  cat(kable(x, row.names = FALSE), sep = "\n", file = file)
  cat_line(file = file)
}

cat_header <- function(..., level = 1, file = "") {
  cat(bold(paste0(strrep("#", level), " ", ...)), "\n", sep = "", file = file)
  cat_line(file = file)
}

cat_bullet <- function(..., file = "") {
  cat_line("* ", ..., file = file)
}

cat_print <- function(x, file = "") {
  if (!identical(file, "")) {
    sink(file)
    on.exit(sink(NULL))
  }

  print(x)
}
```

### PR DESCRIPTION
**Pull request by hadley**
Fixes #8

### CODE REVIEW

**Comment by hadley** [comment]
I wonder if `cat_line()` should have `col` and `bg_col` arguments.

**Comment by gaborcsardi** [comment]
> I wonder if cat_line() should have col and bg_col arguments.

I don't mind. It is also easy just to `cat_line(green("foobar"))`.

**Comment by hadley** [comment]
It's less easy when you're combing multiple fragments:

```R
cat_line("Good ", time, "!", col = "green")
cat_line(crayon::green(paste0("Good ", time, "!"))))
```

**Comment by gaborcsardi** [comment]
Yeah.

**Comment by gaborcsardi** [comment]
@hadley do you want anything else here? If not I can fix the conflict and merge.

**Comment by hadley** [comment]
This is good from my perspective

**Pull request merged**
