### PR TITLE
corrects a typo and be more explicit about RStudio

### PR DESCRIPTION
**Pull request by DanChaltiel**
cf https://github.com/r-lib/cli/issues/554

### CODE REVIEW

**Comment by gaborcsardi** [comment]
@romainfrancois Do you remember that `.run` links need the package to be loaded or attached? Has this behaviour changed since https://github.com/rstudio/rstudio/pull/11318 was merged?

**Comment by romainfrancois** [comment]
I think it just has to be installed. at the end of the day, it goes though this function: 

```r
> .rs.isPackageHyperlinkSafe
function (packageName) 
{
    allowed <- setdiff(c(.packages(), "testthat", "rlang", "devtools", 
        "usethis"), c("base", "stats", "utils"))
    .rs.scalar(packageName %in% allowed)
}
```

if this returns `TRUE`, the code is executed, otherwise just copied into the console.

**Comment by gaborcsardi** [comment]
That's not what I see, though. I need to attach the package, loading does not work.

**Comment by romainfrancois** [comment]
I'll investigate some more. It might have changed in cherry blossom (dev).

**Comment by gaborcsardi** [comment]
Thanks!

**Pull request merged**
