### PR TITLE
Add a print method for spinner

### PR DESCRIPTION
**Pull request by yutannihilation**
Thanks for this neat package! After excited about cool `demo_spinners()`, I got a bit confused how to print spinners by myself. It would be great if there is some easy way to print spinner.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Thanks! There is a way to print them, e.g. 
```r
demo_spinners("dots")
```

**Comment by yutannihilation** [comment]
Thanks for the suggestion, but we might want another version of function without the spinner name (in this case, `dots`) if we want to use spinners in our scripts or packages.

```r
⠏         dots
```

I think it's cool if we have a more general function instead of letting each of us reinvent almost the same functions.

**Comment by gaborcsardi** [comment]
I am not sure what you want to use that method for. The point of a spinner is to show that some computation or I/O is progressing. Obviously, the computation needs to continue, while the spinner is spinning, so you would update a spinner periodically, until the computation is done. E.g. the spinner can be part of a progress bar, and you update it every (couple of) iterations.

I don't see how it is useful to show a spinner while R is not doing anything else.

**Comment by gaborcsardi** [comment]
Maybe I should add an example on how to use a spinner with the `progress` package?

**Comment by yutannihilation** [comment]
Ah, yes. Sorry, I didn't understand the usage correctly... You are right, I close this PR now.

> Maybe I should add an example on how to use a spinner with the `progress` package?

Sounds quite useful! 👍

**Pull request closed without merging**
