### PR TITLE
Fix symbol example

### PR DESCRIPTION
**Pull request by dchiu911**
Using hexadecimal byte representation of the UTF-8 symbols allows them to correctly show on my Linux machine. I used 
```r
lapply(cli:::symbol_utf8, pryr::bytes)
```
to find the mapping. So instead of 
```r
cat(unlist(cli:::symbol_utf8), "\n")
<U+2714> <U+2716> <U+2605> <U+2587> <U+25FB> <U+25FC> <U+25EF> <U+25C9> <U+25CC> <U+25CE> <U+24DE> <U+24E7> <U+24BE> ?<U+20DD> <U+25CF> <U+2024> <U+2500> <U+2550> <U+2026> <U+2026> <U+276F> <U+2139> <U+26A0> <U+2630> <U+263A> <U+0DF4> <U+2665> <U+2191> <U+2193> <U+2190> <U+2192> <U+25C9> <U+25EF> <U+2612> <U+2610> <U+24E7> <U+24BE> <U+2753> <U+2260> <U+2265> <U+2264> <U+00D7> <U+2594> <U+2580> <U+2581> <U+2582> <U+2583> <U+2584> <U+2585> <U+2586> <U+2587> <U+2588> <U+2588> <U+2070> <U+00B9> <U+00B2> <U+00B3> <U+2074> <U+2075> <U+2076> <U+2077> <U+2078> <U+2079> <U+207B> <U+207A> <U+25B6> <U+25A0> <U+25CF>
```
I see
```r
cat(unlist(cli:::symbol_bytes), "\n")
✔ ✖ ★ ▇ ◻ ◼ ◯ ◉ ◌ ◎ ⓞ ⓧ Ⓘ ?⃝ ● ․ ─ ═ … … ❯ ℹ ⚠ ☰ ☺ ෴ ♥ ↑ ↓ ← → ◉ ◯ ☒ ☐ ⓧ Ⓘ ❓ ≠ ≥ ≤ × ▔ ▀ ▁ ▂ ▃ ▄ ▅ ▆ ▇ █ █ ⁰ ¹ ² ³ ⁴ ⁵ ⁶ ⁷ ⁸ ⁹ ⁻ ⁺ ▶ ■ ●
```

### CODE REVIEW

**Comment by gaborcsardi** [comment]
I think this would only work in UTF-8 locales, so we cannot do it.

OTOH,  `cat(unlist(cli:::symbol_utf8), "\n")`  works fine for me in an UTF-8 Linux.

Maybe you just need to set your locales correctly?

**Comment by dchiu911** [comment]
Sounds good. I added a `invisible(Sys.setlocale(locale = "en_US.UTF-8"))` to my `.Rprofile`.

**Comment by gaborcsardi** [comment]
Oh, wait, so this is a different PR now....

**Comment by gaborcsardi** [comment]
Thanks!

**Pull request merged**
