### PR TITLE
Support alert details

### LINKED ISSUE #211: Multi-line alerts (not just from wrapping, but explicit line breaking)
Is there a better way to achieve this? Where by "this" I mean putting the `path` text on its own line, indented nicely with respect to `header`. This looks the way I want but feels pretty goofy.

``` r
reprex_path <- function(header, path, .envir = parent.frame()) {
  cli::cli_alert_success(header, .envir = .envir)
  cli::cli_ul()
  cli::cli_li()
  cli::cli_text("{.file {path}}")
}

reprex_path("Lorem ipsum dolor sit amet", "path/to/a/file")
#> ✓ Lorem ipsum dolor sit amet
#>   path/to/a/file
```

<sup>Created on 2021-01-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

Screen Shot 2021-01-14 at 4 31 16 PM

### PR DESCRIPTION
**Pull request by gaborcsardi**
Closes #211.

### CODE REVIEW

**Comment by jennybc** [comment]
I haven't played with this (yet), but I assume I know what it does from discussion in #211.

A high-level comment on the interface: it's interesting to compare this to `rlang::abort()` and friends. Where the `message` is a character vector that is processed in a very specific way:

> Character vectors are formatted with `format_error_bullets()`. The first element defines a message header and the rest of the vector defines bullets. Bullets named `i` and `x` define info and error bullets respectively, with special Unicode and colour formatting applied if possible.

(Note: there's a feature request to make it possible to suppress the bullet entirely, which is absolutely related to these multi-line alerts https://github.com/r-lib/rlang/issues/1130.)

I am certainly using `cli_alert()`s and `rlang::abort()` in ways that feel similar and it would be nice to make their usage as similar as possible.

**Comment by gaborcsardi** [comment]
Taking a single `message` is a breaking change, unfortunately. >150 packages use cli already, and it is pretty hard to see what we would break with this. I would guess not much, but still.

**Comment by jennybc** [comment]
> Taking a single message is a breaking change, unfortunately.

Is it, though? My understanding of current `cli::cli_alert()` is that `text` is a string, i.e. a length-1 character vector.

So making it more general and accepting length > 1 seems like a non-breaking change.

Also, there's the fact that cli is used to make messages, so cli change seems fairly unlikely to truly break another package. IDK ... it doesn't seem like a deal-killer to me. How many of these packages use `cli_alert()`? Figuring out whether we can make this change without too much pain is something I'd be happy to help out with.

**Comment by jennybc** [comment]
Quick-and-dirty search of CRAN packages for `cli_alert()`: 

"Us":pak, cliapp, reprex, tune
Other people: trans, oysteR, rgrassdoc, RxODE

And the usage doesn't really look like this change would break anything. I realize this isn't definitive, but encouraging.

**Comment by gaborcsardi** [comment]
cli collapses `text`, so it is a breaking change. It "breaks" code like this:
https://github.com/r-lib/pkgdepends/blob/ba140e34ecfa035a4a99dfe43a9e389cec45ff93/R/download-progress-bar.R#L138

Not hard to fix, but then I need a new pkgdepends (maybe pkgcache, etc.) release before the cli release. Otherwise the output will messed up.

If you want the same interface as `rlang::abort()`, then we can have a new function instead.

**Comment by jennybc** [comment]
> If you want the same interface as rlang::abort(), then we can have a new function instead.

That sounds like the way to go. As discussed in #211, there are other reasons to give this its own name / function.

**Pull request merged**
