### PR TITLE
Add an API over crayon

### LINKED ISSUE #51: Provide shim over crayon
So you don't need to import both crayon and cli.

Would also use `paste0()` instead of `paste()`

### PR DESCRIPTION
**Pull request by gaborcsardi**
This includes the builtin crayon functions, and
also `crayon::make_style()` and `crayon::combine_styles()`.

The ANSI support detection functions are currently not
included, but they will be in the future.

Closes #51

### CODE REVIEW

**Comment by krlmlr** [comment]
Would you consider to turn _crayon_ into a soft dependency, so that styling is a no-op if _crayon_ is missing? We're working on reducing the number of hard dependencies in _tibble_.

**Comment by gaborcsardi** [comment]
@krlmlr Yeah, maybe. OTOH crayon is a *really* light weight package. Well, except for the README images, which I'll remove from crayon, actually, and just host on GH. 

Actually the same applies to cli, that should also not have the images in the package, but it is slightly tricky to to have a nice README then.

So, yeah, I think after the images are removed, I really see no reason why you would not want crayon.

**Comment by gaborcsardi** [comment]
> I don't mind it, I just don't want to make it mandatory

But really, why?

**Comment by gaborcsardi** [comment]
Thinking about it more, I don't mind doing this, even though I am worried that there'll be some unfortunate consequences:
* The default output will be worse for a lot of people, because there is no way they've heard about crayon. And this applies to all of our packages, once we start using ANSI colors through cli.
* Making the UI better will be an "expert tip", i.e. "Did you know that if you install the crayon package...", whereas it should be the default.
* People will think that you need to install `Suggest`-ed packages for the better / complete functionality, which is mostly wrong, because for us these are typically build-time dependencies.
* Output testing will be more error-prone for everyone depending on cli, because if they have crayon, then they'll not test without it, and the CRAN etc. will run *without* it, unless they `Suggest` is explicitly.

Whereas the benefits are:
* Avoiding the download of a couple of kBytes, occasionally.
* Is there anything else?

**Comment by gaborcsardi** [comment]
@krlmlr OK, crayon is optional now.

**Comment by hadley** [comment]
I'm not sure making crayon optional actually helps. If cli doesn't import crayon, what will? Will we have to add cli and crayon to the suggests of every package? That seems undesirable.

**Comment by krlmlr** [comment]
The _tidyverse_ package could import _crayon_. This is about making _tibble_ as lightweight as possible, so that packages that merely want to present tibbles to their callers can import it without pulling in all the dependencies.

**Comment by gaborcsardi** [comment]
> merely want to present tibbles to their callers

I am not sure what you mean by "present" here. If you mean "print out nicely on the screen", then I think that would ideally involve colors.

If you mean, just use tibbles internally, without the need of pretty-printing, then I agree, that would make sense, especially when tibble is used within a package. In this case, however, tibble should not depend on cli at all, imo.

**Comment by krlmlr** [comment]
Packages that return tibbles (objects of class `"tbl_df"`) should import the _tibble_ package. Otherwise, behavior depends on if _tibble_ is loaded or not.

I agree that we should put some thought into designing the dependency structure here.

**Comment by gaborcsardi** [comment]
> Packages that return tibbles (objects of class "tbl_df") should import the tibble package.

I was not questioning that, and I agree.

I am suggesting that tibble should Suggest cli, and remove the dependency on crayon and fansi completely.

**Comment by hadley** [comment]
I agree with @gaborcsardi. All tidyverse packages should import cli, and cli should should have a lightweight dependency structure. Crayon is a lightweight dependency, so I don’t see the harm in importing it, particularly when it ensures a high quality experience for all users.

**Pull request merged**
